name: Publish image to GitHub Container Registry (ghcr.io)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t ghcr.io/ThiagoCastagnazzi/cinema_tads:latest -f Dockerfile .
          docker push ghcr.io/ThiagoCastagnazzi/cinema_tads:latest
